version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
              
      - run:
          name: Start PIP
          command: pip install -U pip
     - run:
          name: Start selenium
          command: sudo pip install selenium


      - run:
          name: run text file
          command: python text.py
