version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install selenium
          command: |
              wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar -O selenium-server.jar
              Xvfb :7055
              pip install selenium || true

      - run:
          name: run text file
          command: python text.py
